### ISSUE TITLE
The column headers for the offer.csv file

### ISSUE THREAD

**Issue by amarvw** [HQInterview/BI-developer#1]
Hi,
The offer.csv file does not have column headers nor is the table structure in the readme.md file.
Also just to check if the file is really 777 MB in  size.
Please confirm, so that I can move ahead with the assignment.

Regards,
Amar Wattamwar

**Comment by michaljuhas** [comment]
Hi Amar,

I'll get back to you tomorrow.

Michal

On Friday, 13 November 2015, amarvw notifications@github.com wrote:

> Hi,
> The offer.csv file does not have column headers nor is the table structure
> in the readme.md file.
> Also just to check if the file is really 777 MB in size.
> Please confirm, so that I can move ahead with the assignment.
> 
> Regards,
> Amar Wattamwar
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HQInterview/BI-developer/issues/1.

## 

## 

Co-founder & CTO
HotelQuickly

**Comment by michaljuhas** [comment]
Hi Amar,

I added the list of columns to the `Readme.md`, please check it out.

Good luck,
Michal
